### ISSUE TITLE
'Could not load type "CMS.Base.Internal.ContextUtils" from assembly "CMS.Base"' error

### ISSUE THREAD

**Issue by DGibbsCrafted** [brandonhenricks/xperience-community-health-checks#2]
Hi, I'm using this package in Xperience running the latest refresh (30.0.0) and having some issues. It seems to be attempting to load `ContextUtils` from `CMS.Base.Internal` namespace, but it looks like this type has been moved in more recent refreshes and now resides within `CMS.Base`.  Here's an event log error showing the issue:

![image](https://github.com/user-attachments/assets/38aef196-e353-4ce8-80bb-ed4a34ad7a36)

Is this package compatible with the latest refresh? Thanks

**Comment by brandonhenricks** [comment]
It appears they changed the location of the ContextUtils.

I will bump the dependency up to 29.6.0, that should resolve the error

**Comment by DGibbsCrafted** [comment]
@brandonhenricks - thanks very much for the speedy resolution, can confirm that all is working as expected after upgrading to the latest version.
